apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
   manifests:
    - ./infra/k8s/*
build:
  local:
   push: false
  artifacts:
   - image: samdtech/auth
     context: auth
     docker:
        dockerfile: Dockerfile
     sync:
      manual:
       - src: 'src/**/*.ts'
         dest: .
   - image: samdtech/client
     context: client
     docker:
        dockerfile: Dockerfile
     sync:
      manual:
       - src: '**/*.js'
         dest: .
   - image: samdtech/tickets
     context: tickets
     docker:
        dockerfile: Dockerfile
     sync:
      manual:
       - src: 'src/**/*.ts'
         dest: .
